# DataFrame
- 행열을 가진 2차원 자료구조
- 여러 개의 Series 묶음 자료형

In [12]:
from os import name

import numpy as np
import pandas as pd

## DataFrame 생성

In [13]:
# dict -> df 생성
data = {"one": [1.0, 2.0, 3.0], "two": [10, 20, 30], "three": 99}

# dict의 각 item이 하나의 Series로 처리됨
df = pd.DataFrame(data)
print(df['one']) # 'one'열의 Series 선택
print(df['two']) # 'two'열의 Series 선택
df # 자동으로 브로드 캐스팅 == 차수가 다르면 높은 차수에 맞춰서 주는것

0    1.0
1    2.0
2    3.0
Name: one, dtype: float64
0    10
1    20
2    30
Name: two, dtype: int64

   one  two  three
0  1.0   10     99
1  2.0   20     99
2  3.0   30     99

In [17]:
# 여러 개의 dict -> dataframe
data = [{
    "a": 10,
    "b": 20,
}, {
    "a": 30,
    "b": 40,
    "c": 50,
}]

# 하나의 dict -> 하나의 레코드, key는 컬럼으로 처리
df = pd.DataFrame(data)
df # 0 번행의 C열의 NaN == 결측치

    a   b     c
0  10  20   NaN
1  30  40  50.0

In [18]:
# ndarray -> df
arr = np.arange(9).reshape(3, 3)
df = pd.DataFrame(arr, columns=["a", "b", "c"], index=['1일', '2일', '3일'])
df

    a  b  c
1일  0  1  2
2일  3  4  5
3일  6  7  8

In [19]:
# ser -> df
name_ser = pd.Series(['홍길동', '이순신', '강감찬'])
age_ser = pd.Series([20,25,30])
df = pd.DataFrame({'name':name_ser, 'age':age_ser})

In [20]:
# tuple(record) -> dataframe
# 하나의 객체

data = [
    ('홍길동', 20),
    ('이순신', 30),
    ('논개', 43),
]
df = pd.DataFrame.from_records(data, columns=['이름', '나이'])
df

    이름  나이
0  홍길동  20
1  이순신  30
2   논개  43

## DataFrame 속성

In [21]:
data = {
    'Bank client ID':[1, 2, 3, 4],
    'Bank Client Name':['Laila Aly', 'Kate Steve', 'Nicole Mitch', 'Francis Morris'],
    'Net worth [$]':[35000, 3000, 100000, 2000],
    'Years with bank':[4, 7, 10, 15]
}
df = pd.DataFrame(data)
df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [22]:
df.info() #

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Bank client ID    4 non-null      int64
 1   Bank Client Name  4 non-null      str
 2   Net worth [$]     4 non-null      int64
 3   Years with bank   4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 305.0 bytes

In [23]:
df.describe() # df 설명

       Bank client ID  Net worth [$]  Years with bank
count        4.000000       4.000000         4.000000
mean         2.500000   35000.000000         9.000000
std          1.290994   45963.753836         4.690416
min          1.000000    2000.000000         4.000000
25%          1.750000    2750.000000         6.250000
50%          2.500000   19000.000000         8.500000
75%          3.250000   51250.000000        11.250000
max          4.000000  100000.000000        15.000000

In [24]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Bank client ID', 'Bank Client Name', 'Net worth [$]',
       'Years with bank'],
      dtype='str')

In [26]:
print(df.dtypes)
print(df.shape)

Bank client ID      int64
Bank Client Name      str
Net worth [$]       int64
Years with bank     int64
dtype: object
(4, 4)

## DataFrame 메서드

In [29]:
# head(n), tail(n) : 맨 위/ 밑 n개 조회
display(df.head(2))
display(df.tail(2))

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [32]:
# values_counts(): 유일값 분포 확인
df['Years with bank'].value_counts()

Years with bank
4     1
7     1
10    1
15    1
Name: count, dtype: int64

In [37]:
# index 재지정 : 특정 컬럼을 index로 지정
df = df.set_index('Bank Client Name')
df

                  Net worth [$]  Years with bank
Bank Client Name
Laila Aly                 35000                4
Kate Steve                 3000                7
Nicole Mitch             100000               10
Francis Morris             2000               15

## 조회
- 행열조회
    - df.iloc[인덱스]
    - df.loc[라벨]
- 열조회
    - df[컬럼명]

In [38]:
dicts = [
    {'name' : '홍길동', 'job' : '강사', 'age' : 33},
    {'name' : '신사임당', 'age' : 44, 'job' : '영업사원'},
    {'name' : '이순신', 'age' : 38, 'job' : '장군'},
    {'name' : '논개', 'age' : 25, 'job' : '개발'},
    {'name' : '강감찬', 'age' : 47, 'job' : '교수'},
]
df = pd.DataFrame(dicts)
df

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44
2   이순신    장군   38
3    논개    개발   25
4   강감찬    교수   47

### iloc (인덱스 위치)

In [42]:
# 홍길동 행 조회
print(df.iloc[0])
print(type(df.iloc[0])) # Series, df에서 한 행 또는 한 열은 Series 타입이다
print(df.iloc[0].index)
print(df.iloc[0].name) # df의 index == ser의 이름

name    홍길동
job      강사
age      33
Name: 0, dtype: object
<class 'pandas.Series'>
Index(['name', 'job', 'age'], dtype='str')
0

In [44]:
# 슬라이싱 지원
df2 = df.iloc[0:2] # 0, 1 행 -> df 반환
print(type(df2))
df2

<class 'pandas.DataFrame'>

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44

In [45]:
# fancy indexing 지원
df.iloc[[0, 2]]

  name job  age
0  홍길동  강사   33
2  이순신  장군   38

In [51]:
# 단일 값 조회
print(df.iloc[0, 1])

# 여러 행 조회
df.iloc[:2, 1]

강사

0      강사
1    영업사원
Name: job, dtype: str

In [54]:
df2 = df.iloc[:2, :2]
print(type(df2))
df2

<class 'pandas.DataFrame'>

   name   job
0   홍길동    강사
1  신사임당  영업사원

### loc
인데스라벨을 통해 조회

In [55]:
# index명 지정 == 레이블링(labeling)
df.index = ['client1', 'client2', 'client3', 'client4', 'client5']
df

         name   job  age
client1   홍길동    강사   33
client2  신사임당  영업사원   44
client3   이순신    장군   38
client4    논개    개발   25
client5   강감찬    교수   47

In [56]:
print(type(df.loc['client4'])) # Series 타입
df.loc['client4']

<class 'pandas.Series'>

name    논개
job     개발
age     25
Name: client4, dtype: object

In [58]:
# df.loc[3] KeyError

# loc 슬라이싱은 end 값을 포함한다

In [63]:
# loc를 이용한 컬럼 단일 값 조회
print(df.loc['client2', 'job'])

# loc를 이용한 slicing ⭐️⭐️⭐️
print(df.loc['client2':'client4'])

# loc를 이용한 slicing + column 선택
print(df.loc['client2':'client4', 'job'])

print(df.loc['client2':'client4', :'job'])

영업사원
         name   job  age
client2  신사임당  영업사원   44
client3   이순신    장군   38
client4    논개    개발   25
client2    영업사원
client3      장군
client4      개발
Name: job, dtype: str
         name   job
client2  신사임당  영업사원
client3   이순신    장군
client4    논개    개발

### 컬럼라벨

In [65]:
# df['컬럼명'] : 해당 컬럼 시리즈 반환
print(type(df['name'])) # 가로든 세로든 한 줄이면 ser이다
df['name']

<class 'pandas.Series'>

client1     홍길동
client2    신사임당
client3     이순신
client4      논개
client5     강감찬
Name: name, dtype: str

In [69]:
# column label fancy indexing
# df[['name', 'job']] KeyError
# print(type(df['name', 'job']))

In [71]:
# loc + column label
print(df['name'])
print(df.loc[df['name'] == '이순신'])

client1     홍길동
client2    신사임당
client3     이순신
client4      논개
client5     강감찬
Name: name, dtype: str
        name job  age
client3  이순신  장군   38

In [72]:
# boolean indexing (비교 연산)
print(df['age'] > 30)

client1     True
client2     True
client3     True
client4    False
client5     True
Name: age, dtype: bool

In [74]:
# 30세 미만, 개발 직종을 갖는 행 조회

df.loc[(df['age'] < 30) & (df['job'] == '개발')]

        name job  age
client4   논개  개발   25

In [75]:
# - 이름에 '신'이 들어가거나 나이가 40대이상 조회
df[(df['age'] >= 40) | (df['name'].str.contains('신'))]

         name   job  age
client2  신사임당  영업사원   44
client3   이순신    장군   38
client5   강감찬    교수   47

## 행 추가/삭제

## 컬럼 추가/삭제

## 정렬